package com.fare.fareorders;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

public final class GUI {
    public static final String MAIN=ChatColor.DARK_GRAY+"FareOrders", CREATE=ChatColor.DARK_GREEN+"Create Order", ITEMS=ChatColor.DARK_AQUA+"Select Item", BROWSE=ChatColor.DARK_BLUE+"Browse Orders", MINE=ChatColor.DARK_PURPLE+"My Orders", DETAIL=ChatColor.DARK_GRAY+"Order Details";
    private final FareOrders plugin;
    public GUI(FareOrders plugin){this.plugin=plugin;}
    public void openMainMenu(Player p){Inventory i=Bukkit.createInventory(null,54,MAIN);fill(i);i.setItem(20,item(Material.CHEST,ChatColor.GOLD+"Browse Orders","View orders from other players."));i.setItem(22,item(Material.EMERALD,ChatColor.GREEN+"Create Order","Request items from other players."));i.setItem(24,item(Material.BOOK,ChatColor.YELLOW+"My Orders","Manage your orders and deliveries."));i.setItem(49,item(Material.BARRIER,ChatColor.RED+"Close"));p.openInventory(i);}
    public void openCreateOrder(Player p){Inventory i=Bukkit.createInventory(null,54,CREATE);fill(i);OrderSession s=plugin.getOrderSession(p.getUniqueId());String selected=s!=null&&s.getMaterial()!=null?pretty(s.getMaterial()):"Not selected";i.setItem(20,item(s!=null&&s.getMaterial()!=null?s.getMaterial():Material.DIAMOND,ChatColor.AQUA+"Item","Selected: "+selected,"Click to choose an item."));i.setItem(22,item(Material.PAPER,ChatColor.YELLOW+"Quantity",s!=null&&s.getAmount()>0?"Amount: "+s.getAmount():"Click to enter quantity."));i.setItem(24,item(Material.EMERALD,ChatColor.GREEN+"Price",s!=null&&s.getPrice()>0?"Per item: "+plugin.getEconomyManager().format(s.getPrice()):"Click to enter price."));boolean ready=s!=null&&s.getMaterial()!=null&&s.getAmount()>0&&s.getPrice()>0;i.setItem(40,item(ready?Material.LIME_DYE:Material.GRAY_DYE,ready?ChatColor.GREEN+"Confirm Order":ChatColor.GRAY+"Confirm Order",ready?"Reserve funds and create the order.":"Choose an item, quantity and price first."));i.setItem(49,item(Material.BARRIER,ChatColor.RED+"Cancel"));p.openInventory(i);}
    public void openItemSelector(Player p,int page,String filter){Inventory i=Bukkit.createInventory(null,54,ITEMS);fill(i);List<Material> mats=new ArrayList<>();String f=filter==null?"":filter.trim().toLowerCase(Locale.ROOT);for(Material m:Material.values()){if(!m.isItem()||m.isAir())continue;if(!f.isEmpty()&&!m.name().toLowerCase(Locale.ROOT).contains(f))continue;mats.add(m);}mats.sort(Comparator.comparing(Material::name));int max=Math.max(0,(mats.size()-1)/45);page=Math.max(0,Math.min(page,max));OrderSession s=plugin.getOrderSession(p.getUniqueId());if(s!=null)s.setItemPage(page);int start=page*45;for(int n=0;n<45&&start+n<mats.size();n++){Material m=mats.get(start+n);i.setItem(n,item(m,ChatColor.WHITE+pretty(m),"Click to select this item."));}i.setItem(45,item(Material.ARROW,ChatColor.YELLOW+"Previous",page>0?"Previous page.":"First page."));i.setItem(48,item(Material.BARRIER,ChatColor.RED+"Back"));i.setItem(49,item(Material.NAME_TAG,ChatColor.AQUA+"Search",f.isBlank()?"Enter an item name in chat.":"Current: "+f));i.setItem(50,item(Material.BOOK,ChatColor.GRAY+"Page "+(page+1)+"/"+(max+1)));i.setItem(53,item(Material.ARROW,ChatColor.YELLOW+"Next",page<max?"Next page.":"Last page."));p.openInventory(i);}
    public void openBrowse(Player p,int page){Inventory i=Bukkit.createInventory(null,54,BROWSE);fill(i);List<Order> list=plugin.getOrderManager().active();int max=Math.max(0,(list.size()-1)/45);page=Math.max(0,Math.min(page,max));OrderSession s=plugin.getOrderSession(p.getUniqueId());if(s==null)s=plugin.createOrderSession(p.getUniqueId());s.setBrowsePage(page);int start=page*45;for(int n=0;n<45&&start+n<list.size();n++)i.setItem(n,orderIcon(list.get(start+n)));nav(i,page,max);p.openInventory(i);}
    public void openMyOrders(Player p,int page){Inventory i=Bukkit.createInventory(null,54,MINE);fill(i);List<Order> list=plugin.getOrderManager().byOwner(p.getUniqueId());int max=Math.max(0,(list.size()-1)/45);page=Math.max(0,Math.min(page,max));OrderSession s=plugin.getOrderSession(p.getUniqueId());if(s==null)s=plugin.createOrderSession(p.getUniqueId());s.setMinePage(page);int start=page*45;for(int n=0;n<45&&start+n<list.size();n++)i.setItem(n,orderIcon(list.get(start+n)));nav(i,page,max);p.openInventory(i);}
    public void openOrderDetails(Player p,Order o){Inventory i=Bukkit.createInventory(null,54,DETAIL);fill(i);if(o==null){i.setItem(22,item(Material.BARRIER,ChatColor.RED+"Order not found"));p.openInventory(i);return;}OrderSession s=plugin.getOrderSession(p.getUniqueId());if(s==null)s=plugin.createOrderSession(p.getUniqueId());s.setSelectedOrderId(o.getId());boolean mine=o.getOwner().equals(p.getUniqueId());i.setItem(13,item(o.getMaterial(),ChatColor.AQUA+pretty(o.getMaterial()),"Order #"+o.getId(),"Requested: "+o.getAmount(),"Remaining: "+o.getRemaining(),"Delivered: "+o.getDelivered(),"Price: "+plugin.getEconomyManager().format(o.getPrice())+" each","Total: "+plugin.getEconomyManager().format(o.getTotalValue())));if(mine){i.setItem(30,item(Material.HOPPER,ChatColor.GREEN+"Collect Delivered","Items waiting: "+o.getDelivered(),"Click to collect as much as fits."));i.setItem(32,item(Material.BARRIER,ChatColor.RED+"Cancel Order","Refunds all unfulfilled funds.","Delivered items remain claimable."));}else if(!o.isComplete()&&!o.isExpired()){i.setItem(20,item(Material.IRON_INGOT,ChatColor.YELLOW+"Deliver 1","Supply one item."));i.setItem(22,item(Material.GOLD_INGOT,ChatColor.GOLD+"Deliver 64","Supply up to 64 items."));i.setItem(24,item(Material.DIAMOND,ChatColor.AQUA+"Deliver All","Supply as many as you have."));}i.setItem(49,item(Material.ARROW,ChatColor.YELLOW+"Back"));p.openInventory(i);}
    private void nav(Inventory i,int page,int max){i.setItem(45,item(Material.ARROW,ChatColor.YELLOW+"Previous",page>0?"Previous page.":"First page."));i.setItem(49,item(Material.BARRIER,ChatColor.RED+"Back"));i.setItem(50,item(Material.BOOK,ChatColor.GRAY+"Page "+(page+1)+"/"+(max+1)));i.setItem(53,item(Material.ARROW,ChatColor.YELLOW+"Next",page<max?"Next page.":"Last page."));}
    private ItemStack orderIcon(Order o){return item(o.getMaterial(),ChatColor.AQUA+pretty(o.getMaterial()),"Order #"+o.getId(),"Remaining: "+o.getRemaining()+"/"+o.getAmount(),"Price: "+plugin.getEconomyManager().format(o.getPrice())+" each","Delivered: "+o.getDelivered(),"Click for details.");}
    private void fill(Inventory i){ItemStack f=item(Material.GRAY_STAINED_GLASS_PANE," ");for(int n=0;n<i.getSize();n++)i.setItem(n,f);}
    private ItemStack item(Material m,String name,String... lore){ItemStack s=new ItemStack(m==null?Material.BARRIER:m);ItemMeta meta=s.getItemMeta();if(meta==null)return s;meta.setDisplayName(name);if(lore.length>0)meta.setLore(List.of(lore));s.setItemMeta(meta);return s;}
    public static String pretty(Material m){StringBuilder b=new StringBuilder();for(String part:m.name().toLowerCase(Locale.ROOT).split("_")){if(b.length()>0)b.append(' ');b.append(Character.toUpperCase(part.charAt(0))).append(part.substring(1));}return b.toString();}
}
